# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-03-03 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='mood',
            field=models.FloatField(blank=True, null=True, verbose_name='mood'),
        ),
    ]
