# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-03-03 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diaryentry_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='mood',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='negativeness',
            field=models.FloatField(blank=True, null=True, verbose_name='Negativeness'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='neutrality',
            field=models.FloatField(blank=True, null=True, verbose_name='Neutrality'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='positiveness',
            field=models.FloatField(blank=True, null=True, verbose_name='Positiveness'),
        ),
    ]
