from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^$',
        views.CurrentDayRedirectView.as_view(),
        name='current-day'
    ),
    url(
        r'^date-(?P<date>[\w-]+)/$',
        views.EntryPreviewView.as_view(),
        name='entry-preview'
    ),
    url(
        r'^date-(?P<date>[\w-]+)/edit/$',
        views.EntryEditView.as_view(),
        name='entry-edit'
    ),
    url(
        r'^date-(?P<date>[\w-]+)/update/$',
        views.EntryUpdateView.as_view(),
        name='entry-edit'
    ),
    url(
        r'^calendar/$',
        views.CalendarView.as_view(),
        name='calendar'
    ),
    url(
        r'^category/$',
        views.CategoryView.as_view(),
        name='category'
    ),
    url(
        r'^category/add/$',
        views.CategoryAdd.as_view(),
        name='category_add'
    ),
    url(
        r'^category/update/(?P<category>.+)$',
        views.CategoryUpdate.as_view(),
        name='category_update'
    ),
    url(
        r'^category/save/update/(?P<category>.+)$',
        views.CategorySaveUpdate.as_view(),
        name='category_save_update'
    ),
    url(
        r'^category/delete/$',
        views.CategoryDelete.as_view(),
        name='category_delete'
    ),
    url(
        r'^tasks/$',
        views.TaskPreviewView.as_view(),
        name='task-preview'
    ),
    url(
        r'^tasks/preview/$',
        views.TaskPreviewViewDate.as_view(),
        name='task-preview-date'
    ),
    url(
        r'^tasks/add/$',
        views.TaskAdd.as_view(),
        name='task-preview-date'
    ),
    url(
        r'^tasks/save/$',
        views.TaskSave.as_view(),
        name='task-save'
    ),
    url(
        r'^tasks/delete/$',
        views.TaskDelete.as_view(),
        name='task-delete'
    ),
    url(
        r'^tasks/update/(?P<task_id>[0-9]+)$',
        views.TaskUpdate.as_view(),
        name='task_update'
    ),
    url(
        r'^tasks/update/save/(?P<task_id>.+)$',
        views.TaskUpdateSave.as_view(),
        name='task_update_save'
    ),
    url(
        r'^analysis/$',
        views.StatisticsCategories.as_view(),
        name='analysis'
    ),
    url(
        r'^analysis/view/$',
        views.StatisticsPreview.as_view(),
        name='analysis_view'
    ),
    url(
        r'^search/$',
        views.SearchView.as_view(),
        name='search'
    ),
]
