# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-02-14 13:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180130_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'font': 'Caveat', 'language': 'en', 'theme': 'light'}, null=True, verbose_name='settings'),
        ),
    ]
